### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by maxcanna**
Ref. #4

### CODE REVIEW

**Comment by maxcanna** [comment]
@adespresso/developers could you visit the [stage](https://branch-bookkeeper.herokuapp.com), install the [bookmarklet](https://bootswatch.com/help/) and lmk if the current theme is the best one as I think?

**Comment by carlo1138** [comment]
I have Tampermonkey installed, but the install link doesn't work 😭

**Comment by maxcanna** [comment]
@carlo1138 this PR adds homepage, user script is being developed in #9 and will be integrated once ready (we've our best FE dev on it, don't worry). My fault, I should've written in the PR desc.

Anything else apart from that? 😃

**Comment by carlo1138** [comment]
🍭

**Comment by maxcanna** [comment]
Shame on me, I need to add a message when there are no bookings at all 🇯🇵

**Pull request merged**
