### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by maxcanna**
Add `docker` support to ease development and deployment

### CODE REVIEW

**Comment by maxcanna** [comment]
@riquito could you give me green light with this one? 😀

**Comment by demerzel3** [comment]
Really great, but.. can we have https support to ease the development of the monkey script? If you recall, we need that to use the fake chrome extension in dev.

**Comment by demerzel3** [comment]
Also, I see a warning while running `docker/init.sh`, if possible I would get rid of that, too:

```
$ docker/init.sh
Stopping branchbookkeeper_branch-bookkeeper_1 ... done
Stopping branchbookkeeper_redis_1 ... done
WARNING: --all flag is obsolete. This is now the default behavior of `docker-compose rm`
Going to remove branchbookkeeper_branch-bookkeeper_1, branchbookkeeper_redis_1
Removing branchbookkeeper_branch-bookkeeper_1 ... done
Removing branchbookkeeper_redis_1 ... done
Creating branchbookkeeper_redis_1
Creating branchbookkeeper_branch-bookkeeper_1
```

**Comment by maxcanna** [comment]
@demerzel3 thank you for your feedback. I was sure to have removed those warnings. Never mind. First thing in the morning. Regarding the https support I've already planned a development to add it (in the dev env) along with the automatic redirect from http

**Pull request merged**
